/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testNG_1;

// Base class
class Base {
    // Base method - takes no arguments
    public void display() {
        System.out.println("Base display()");
    }
}